name: Node CIwwwww

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        hexo clean
        hexo g
        git clone https://git.dev.tencent.com/pond/gking.git .deploy_git
        cd .deploy_git
        git checkout master
        mv .deploy_git/.git/ ./public/
        cd ./public
        git config user.name "pond"
        git config user.email "greeedyboy@163.com"
        git add
        git commit -m "Builder at `date +"%Y-%m-%d %H:%M"`"
        git push --force --quiet "https://pond:$34f9589b7045a778ca55728513e714eb04cd190e@git.dev.tencent.com/pond/gking.git" master:master
        
      env:
        CI: true
        
